export const calendarTheme = (colors: any) => ({
  backgroundColor: colors.calendar.background,
  calendarBackground: colors.calendar.background,
  textSectionTitleColor: colors.calendar.textSection,
  selectedDayBackgroundColor: colors.calendar.selectedDay,
  selectedDayTextColor: colors.calendar.selectedDayText,
  todayTextColor: colors.calendar.today,
  dayTextColor: colors.calendar.dayText,
  textDisabledColor: colors.calendar.disabledText,
  dotColor: colors.calendar.dot,
  selectedDotColor: colors.calendar.selectedDot,
  arrowColor: colors.calendar.arrow,
  monthTextColor: colors.calendar.monthText,
  indicatorColor: colors.calendar.selectedDay,
  textDayFontFamily: 'System',
  textMonthFontFamily: 'System',
  textDayHeaderFontFamily: 'System',
  textDayFontWeight: '300' as const,
  textMonthFontWeight: 'bold' as const,
  textDayHeaderFontWeight: '500' as const,
  textDayFontSize: 13,
  textMonthFontSize: 16,
  textDayHeaderFontSize: 12,
});